<a href="https://colab.research.google.com/github/truptikalal22/Playstore_project/blob/main/playstore_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datasets/playstore_dataset.csv')

/tmp/ipykernel_6015/1290411646.py:1: DtypeWarning: Columns (7,12,29,30,33,35,37,38,40,41,42,43,44,45,46,47,48,49,50,52,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datasets/playstore_dataset.csv')

In [4]:
df.shape

(450795, 57)

In [5]:
df.columns

Index(['App Name', 'App Id', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Free', 'Price', 'Currency', 'Size',
       'Minimum Android', 'Developer Id', 'Developer Website',
       'Developer Email', 'Released', 'Last update', 'Privacy Policy',
       'Content Rating', 'Ad Supported', 'In app purchases', 'Editor Choice',
       'Summary', 'Reviews', 'Android version Text', 'Developer',
       'Developer Address', 'Developer Internal ID', 'Version', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37',
       'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41',
       'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45',
       'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49',
       'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53',
       'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56'],
      dtype='object')

In [6]:
unnames_col=df.columns[df.columns.str.startswith("Unnamed")]
print(df[unnames_col].notna().sum())

Unnamed: 29    2
Unnamed: 30    2
Unnamed: 31    2
Unnamed: 32    2
Unnamed: 33    2
Unnamed: 34    2
Unnamed: 35    2
Unnamed: 36    2
Unnamed: 37    2
Unnamed: 38    2
Unnamed: 39    2
Unnamed: 40    2
Unnamed: 41    1
Unnamed: 42    2
Unnamed: 43    2
Unnamed: 44    2
Unnamed: 45    1
Unnamed: 46    2
Unnamed: 47    1
Unnamed: 48    2
Unnamed: 49    2
Unnamed: 50    2
Unnamed: 51    2
Unnamed: 52    2
Unnamed: 53    2
Unnamed: 54    0
Unnamed: 55    2
Unnamed: 56    2
dtype: int64

In [7]:
df = df.drop(columns=unnames_col)

In [8]:
df.to_csv("/content/drive/MyDrive/Colab Notebooks/datasets/Playstore_cleaned.csv", index=False)

In [9]:

df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datasets//Playstore_cleaned.csv')

/tmp/ipykernel_6015/394453992.py:1: DtypeWarning: Columns (7,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datasets//Playstore_cleaned.csv')

In [10]:
df.shape

(450795, 29)

In [11]:
df.columns

Index(['App Name', 'App Id', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Free', 'Price', 'Currency', 'Size',
       'Minimum Android', 'Developer Id', 'Developer Website',
       'Developer Email', 'Released', 'Last update', 'Privacy Policy',
       'Content Rating', 'Ad Supported', 'In app purchases', 'Editor Choice',
       'Summary', 'Reviews', 'Android version Text', 'Developer',
       'Developer Address', 'Developer Internal ID', 'Version'],
      dtype='object')

In [12]:
df['App Name'].isnull().sum()

np.int64(13)

In [13]:
df=df.dropna(subset=['Price'])

In [14]:
df.values

array([['Logistics Management', 'com.eniseistudio.logistics_management',
        'Education', ...,
        '7115 N Muscatel Ave San Gabriel, CA 91775 United States',
        4.65645e+18, '1.1.5'],
       ['Estados Unidos Noticias',
        'com.eniseistudio.news.estados_unidos', 'News & Magazines', ...,
        '7115 N Muscatel Ave San Gabriel, CA 91775 United States',
        4.65645e+18, '1.2.3'],
       ['Dental Assistant', 'com.eniseistudio.dental_assistant',
        'Education', ...,
        '7115 N Muscatel Ave San Gabriel, CA 91775 United States',
        4.65645e+18, '1.1.5'],
       ...,
       ['Rap Music Maker : Rap Beats Music Recording Studio',
        'com.fancy.rapmusicmakerstudio', 'Music & Audio', ..., nan,
        5.36213e+18, '2.3'],
       ['Meetz - Cloud Meetings and Classes', 'org.ssz.meet',
        'Communication', ..., nan, 7.18566e+18, 'Varies with device'],
       ['SWACU Mobile', 'com.southwest.mobile', 'Finance', ...,
        '2430 Shorecrest Drive\nDallas, TX 75235', 7.66834e+18, '19.4']],
      dtype=object)

In [15]:
df.sample()

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Free,Price,Currency,...,Ad Supported,In app purchases,Editor Choice,Summary,Reviews,Android version Text,Developer,Developer Address,Developer Internal ID,Version
141460,d20 Character Sheet,com.android.ash.charactersheet,Tools,3.97,387.0,"5,000+",5000.0,True,0.0,USD,...,NaN,True,False,The d20 Character Sheet handles your DnD and P...,262.0,8.0 and up,Torsten Wiederkehr,Mozartring 2\n63868 GroÃŸwallstadt,8.029810e+18,4.4.0

In [16]:
df.head(2)

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Free,Price,Currency,...,Ad Supported,In app purchases,Editor Choice,Summary,Reviews,Android version Text,Developer,Developer Address,Developer Internal ID,Version
0,Logistics Management,com.eniseistudio.logistics_management,Education,4.090909,66.0,"10,000+",10000.0,True,0.0,USD,...,True,False,False,Leading Online Learning and Training System in...,28.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656450e+18,1.1.5
1,Estados Unidos Noticias,com.eniseistudio.news.estados_unidos,News & Magazines,4.000000,8.0,"1,000+",1000.0,True,0.0,USD,...,True,False,False,Top Stories\r\nWorld\r\nEntertainment\r\nSport...,3.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656450e+18,1.2.3

In [17]:
df.tail(2)

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Free,Price,Currency,...,Ad Supported,In app purchases,Editor Choice,Summary,Reviews,Android version Text,Developer,Developer Address,Developer Internal ID,Version
450793,Meetz - Cloud Meetings and Classes,org.ssz.meet,Communication,NaN,NaN,"5,000+",5000.0,True,0.0,USD,...,NaN,False,False,Virtual meetings for everyone,NaN,Varies with device,INVENTRIX,NaN,7.185660e+18,Varies with device
450794,SWACU Mobile,com.southwest.mobile,Finance,2.86,150.0,"10,000+",10000.0,True,0.0,USD,...,NaN,False,False,SWACU Mobile,80.0,4.4 and up,Southwest Airlines Federal Credit Union,"2430 Shorecrest Drive\nDallas, TX 75235",7.668340e+18,19.4

In [18]:

df.columns

Index(['App Name', 'App Id', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Free', 'Price', 'Currency', 'Size',
       'Minimum Android', 'Developer Id', 'Developer Website',
       'Developer Email', 'Released', 'Last update', 'Privacy Policy',
       'Content Rating', 'Ad Supported', 'In app purchases', 'Editor Choice',
       'Summary', 'Reviews', 'Android version Text', 'Developer',
       'Developer Address', 'Developer Internal ID', 'Version'],
      dtype='object')

In [19]:
df['App Id'].unique()

array(['com.eniseistudio.logistics_management',
       'com.eniseistudio.news.estados_unidos',
       'com.eniseistudio.dental_assistant', ..., 'com.dar.prison.escape',
       'com.earnit.rb7', 'com.wholesale7.yxm'], dtype=object)

In [20]:
df['App Id'].isnull().sum()

np.int64(0)

In [21]:
df=df.drop(columns=['App Id'])

In [22]:
df[['Category']]

                Category
0              Education
1       News & Magazines
2              Education
3              Education
4              Education
...                  ...
450790      Productivity
450791   Personalization
450792     Music & Audio
450793     Communication
450794           Finance

[450703 rows x 1 columns]

In [23]:
df['Category'].isnull().sum()

np.int64(0)

In [24]:
df=df.dropna(subset=['Category'])

In [25]:
df['Price'].isnull().sum()

np.int64(0)

In [26]:
df['Price'].isnull().mean()*100

np.float64(0.0)

In [27]:
df['Price']=df['Price'].fillna(df['Price'].median())

In [28]:
df['Price'].unique()

array([  0.      ,   6.49    ,   2.99    ,   3.99    ,   3.49    ,
         0.99    ,   1.99    ,   4.99    ,  10.99    ,   5.49    ,
         1.49    ,   5.99    ,   2.49    ,  24.99    ,   5.      ,
        10.      ,   6.99    ,   7.49    , 174.99    ,   5.29    ,
         1.2     ,  22.99    ,   3.      ,  12.99    ,  13.99    ,
        18.99    ,   1.18    ,   1.      ,  14.99    ,   9.99    ,
         8.99    ,   7.99    , 109.99    ,  19.99    ,   4.49    ,
         2.84    ,   2.88    ,   2.65    ,   3.01    ,  33.99    ,
        89.99    ,   1.6     ,   9.49    ,   1.09    ,   8.      ,
         4.      , 100.      ,   6.04    ,   2.19    ,  11.99    ,
         4.29    ,  16.99    ,  25.99    ,  13.55    ,   1.08    ,
         2.9     ,  19.95    ,   4.89    ,  20.99    ,  29.99    ,
        27.99    ,  17.99    ,  15.99    ,   1.15    ,  59.99    ,
        79.99    ,  23.99    ,   3.69    ,  35.99    , 164.99    ,
         8.49    ,   3.9     ,  36.99    ,   9.23    ,   4.75    ,
        17.84    ,   2.29    ,   2.5     ,   6.      ,   1.67    ,
         1.8     , 389.99    ,   2.93    ,   2.53    ,   1.74    ,
       249.99    ,  99.99    ,  54.99    ,  26.99    ,   1.92    ,
        28.99    ,  21.99    ,   1.06    ,   1.05    ,   1.29    ,
        94.99    ,   2.42    ,   2.23    ,  27.5     ,   1.75    ,
       139.99    ,   3.11    ,  37.99    ,  38.99    ,   2.34    ,
         7.21    ,   4.9     ,   1.98    ,   2.72    ,   1.95    ,
         1.51    ,   2.45    ,   1.5     ,  10.88    ,  42.99    ,
         1.39    ,   1.03    ,   1.07    ,   1.25    ,   5.46    ,
        49.99    ,   2.95    ,   4.84    ,  34.99    ,  74.99    ,
         2.73    ,  64.99    ,  69.99    ,   3.75    ,   3.39    ,
         1.3     ,   1.22    ,   1.79    ,   1.19    ,   3.5     ,
         1.69    ,   2.      , 162.99    ,   1.52    ,   1.37    ,
       399.99    , 379.99    ,   4.96    ,  30.42    ,  13.6     ,
         4.69    ,   2.28    ,  41.99    , 349.99    ,   2.85    ,
         1.34    ,   2.79    ,   1.35    ,   1.45    ,   3.24    ,
        45.99    ,   9.95    ,   1.84    ,   3.29    ,   2.31    ,
         8.28    ,  24.001071,   3.59    ,  69.      ,  12.49    ,
        49.      ,  39.99    ,   2.89    ,  12.35    ,  12.19    ,
        11.45    ,  40.99    ,   5.079014,   1.85    ,   1.1     ,
        20.      ,   1.01    ,   4.98    ,   1.63    ,   1.04    ,
         1.94    ,   2.14    ,   1.78    ,   8.19    ,  17.98    ,
         4.71    ,   3.95    ,   3.89    ,   3.32    ,   5.95    ,
         7.73    ,   2.98    ,   1.97    ,   2.74    ,   4.85    ,
        19.85    ,   5.85    ,  29.85    ,   7.56    ,   3.624404,
         1.21    ,   1.59    ,   1.65    ,  32.99    ,   2.39    ,
         2.36    ,   2.1     ,  91.35    ,  25.27    ,   5.48    ,
       400.      ,  30.99    , 199.99    ,   1.42    ,   5.36    ,
        31.99    ,   2.59    ,  44.99    ,  13.53    ,   6.77    ,
         4.48    , 119.99    ,   1.77    ,   1.32    ,   1.11    ,
         2.02    ,   1.91    ,   1.33    ,   1.72    ,   9.9     ,
         2.8     ,  19.98    ,   8.4     ,   1.13    ,   3.72    ,
       129.99    ,   1.81    ,   2.3     , 114.99    ,   2.37    ,
        31.69    ,   4.848701, 149.99    ,   6.606355,   3.97    ,
         2.97    ,   1.7     ,  14.9     ,   1.944655,   2.77    ,
         3.05    ,   4.86    ,   1.86    ,   5.63    ,  29.95    ,
         2.13    , 104.99    ,   8.9     ,   4.5     ,   7.79    ,
         1.93    ,   3.38    ,   2.41    ,   2.09    ,  34.25    ,
        12.      , 338.99    ,  18.      ,   3.17    ,   2.06    ,
         3.45    ,   5.31    ,   3.8     ,  13.12    ,   2.2     ,
        39.79    ,   3.44    ,  11.9     ,   6.73    ,   3.74    ,
         4.04    ,   1.27    ,   5.97    ,  47.99    ,   2.7     ,
        15.      ,  11.      ,  12.5     ,   3.98    ,   3.85    ,
         1.26    ,   2.91    ,   2.94    ,   5.64    ,   5.65    ,
         5.66    ,   9.72    ,   9.      ,  49.19    ,  26.39    ,
        77.99    , 191.99    ,  56.39    , 233.99    ,  51.59    ,
        48.8     ,  25.19    ,  45.55    ,  44.77    ,  46.4     ,
        20.39    ,  42.71    ,  34.79    ,  65.38    ,  57.59    ,
        47.77    ,  43.19    ,  44.05    ,  46.29    ,  40.79    ,
        39.59    ,  53.44    ,  54.54    ,  44.98    ,  29.48    ,
        84.99    ,  21.6     ,  53.52    ,  41.82    ,  56.62    ,
        53.45    ,  55.77    ,  42.66    ,  53.81    ,  49.6     ,
       143.99    ,  54.82    ,  56.48    ,  32.39    ,  46.3     ,
        48.75    ,  56.9     ,  71.99    ,  50.28    ,   1.16    ,
         4.95    ,  16.54    ,   4.17    ,  29.      ,  36.001606,
         7.9     ,   6.9     ,   2.61    ,  67.5     ,   1.931923,
         1.89    ,   2.86    ,   7.89    ,   1.28    ,   7.13    ,
         5.2     ,   5.62    ,   4.77    ,   8.15    ,   1.4     ,
         1.12    ,   5.61    ,   2.4     ,   1.02    , 339.99    ,
       214.99    ,  16.22    ,   7.33    ,   2.64    ,   1.48    ,
         1.58    ,   7.34    ,   2.43    ,   3.608315,   1.73    ,
         8.5     ,   7.      ,  43.99    ,  26.42    ,   3.84    ,
         1.56    ,   1.46    ,   4.33    ,   4.42    ,   9.85    ,
         2.27    ,   3.86    ,   2.35    ,   3.82    ,   0.684268,
        19.      ,  21.      ,   2.303133,   2.363741,   2.060698,
         2.78    ,   3.62    ,   9.6     ,   2.58    ,   2.33    ,
         2.46    ,   2.26    ,   6.98    ,   7.01    ,   7.58    ,
         7.55    ,  89.      ,   7.81    ,   3.79    ,   1.567891,
       329.99    ,  12.91    ,   4.62    , 134.99    ,   4.25    ,
         2.25    ,  10.75    ,   2.11    ,   2.55    ,   2.82    ,
         2.69    ,   5.56    ,   7.77    ,   3.48    ,   1.88    ,
         2.21    ,   2.75    ,   1.87    ,   1.36    ,   6.72    ,
       244.99    ,   1.66    ,   1.55    ,   1.68    ,   1.64    ,
         1.57    ,   4.45    ,  48.99    ,  36.      ,   3.3     ,
         1.54    , 264.99    ,   3.54    , 169.99    , 124.99    ,
         1.23    ,   2.08    ,   1.9     ,  19.9     ,   7.06    ,
         3.67    ,   1.38    ,   8.37    ,  99.9     ,   5.42    ,
         3.25    ,   3.33    ,   2.76    ,   1.168354,   5.33    ,
         4.3     ,   3.1     ,   1.41    ,   2.54    ,   2.52    ,
         1.47    ,  46.99    ,   3.13    ,   2.44    ,   2.01    ,
         1.96    ,   2.24    ])

In [29]:
type(df['Price'])

pandas.core.series.Series

In [30]:
df['Price']=pd.to_numeric(df['Price'],errors='coerce')
df['Price']=df['Price'].round(1)

In [31]:
df['Price'].unique ()

array([  0. ,   6.5,   3. ,   4. ,   3.5,   1. ,   2. ,   5. ,  11. ,
         5.5,   1.5,   6. ,   2.5,  25. ,  10. ,   7. ,   7.5, 175. ,
         5.3,   1.2,  23. ,  13. ,  14. ,  19. ,  15. ,   9. ,   8. ,
       110. ,  20. ,   4.5,   2.8,   2.9,   2.6,  34. ,  90. ,   1.6,
         9.5,   1.1, 100. ,   2.2,  12. ,   4.3,  17. ,  26. ,  13.6,
         4.9,  21. ,  30. ,  28. ,  18. ,  16. ,  60. ,  80. ,  24. ,
         3.7,  36. , 165. ,   8.5,   3.9,  37. ,   9.2,   4.8,  17.8,
         2.3,   1.7,   1.8, 390. , 250. ,  55. ,  27. ,   1.9,  29. ,
        22. ,   1.3,  95. ,   2.4,  27.5, 140. ,   3.1,  38. ,  39. ,
         7.2,   2.7,  10.9,  43. ,   1.4,  50. ,  35. ,  75. ,  65. ,
        70. ,   3.8,   3.4, 163. , 400. , 380. ,  30.4,   4.7,  42. ,
       350. ,   3.2,  46. ,   3.3,   8.3,   3.6,  69. ,  12.5,  49. ,
        40. ,  12.4,  12.2,  11.4,  41. ,   5.1,   2.1,   8.2,   7.7,
        19.8,   5.8,  29.8,   7.6,  33. ,  91.4,  25.3,  31. , 200. ,
         5.4,  32. ,  45. ,  13.5,   6.8, 120. ,   9.9,   8.4, 130. ,
       115. ,  31.7, 150. ,   6.6,  14.9,   5.6, 105. ,   8.9,   7.8,
        34.2, 339. ,  13.1,  39.8,  11.9,   6.7,  48. ,   5.7,   9.7,
        49.2,  26.4,  78. , 192. ,  56.4, 234. ,  51.6,  48.8,  25.2,
        45.6,  44.8,  46.4,  20.4,  42.7,  34.8,  65.4,  57.6,  47.8,
        43.2,  44. ,  46.3,  40.8,  39.6,  53.4,  54.5,  29.5,  85. ,
        21.6,  53.5,  41.8,  56.6,  55.8,  53.8,  49.6, 144. ,  54.8,
        56.5,  32.4,  56.9,  72. ,  50.3,  16.5,   4.2,   7.9,   6.9,
        67.5,   7.1,   5.2, 340. , 215. ,  16.2,   7.3,   4.4,   9.8,
         0.7,   9.6,  89. , 330. ,  12.9,   4.6, 135. ,  10.8, 245. ,
       265. , 170. , 125. ,  19.9,  99.9,  47. ])

In [32]:
free_app = (df['Price']== 0 ).sum()
paid_app = (df['Price']> 0).sum()

print("Free apps ",free_app)
print("Paid apps",paid_app)

Free apps  422466
Paid apps 28237

In [33]:
df['App Type'] = df['Price'].apply(
    lambda x: 'Free' if x == 0 else 'Paid')

In [34]:
df['App Type'].value_counts()

App Type
Free    422466
Paid     28237
Name: count, dtype: int64

In [35]:
df.head()

,App Name,Category,Rating,Rating Count,Installs,Minimum Installs,Free,Price,Currency,Size,...,In app purchases,Editor Choice,Summary,Reviews,Android version Text,Developer,Developer Address,Developer Internal ID,Version,App Type
0,Logistics Management,Education,4.090909,66.0,"10,000+",10000.0,True,0.0,USD,5.8M,...,False,False,Leading Online Learning and Training System in...,28.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656450e+18,1.1.5,Free
1,Estados Unidos Noticias,News & Magazines,4.000000,8.0,"1,000+",1000.0,True,0.0,USD,5.3M,...,False,False,Top Stories\r\nWorld\r\nEntertainment\r\nSport...,3.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656450e+18,1.2.3,Free
2,Dental Assistant,Education,3.866667,15.0,"10,000+",10000.0,True,0.0,USD,5.7M,...,False,False,"Dental Assistant: Study Dental Assistant, Dent...",3.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656450e+18,1.1.5,Free
3,Medical Assistant,Education,4.000000,18.0,"5,000+",5000.0,True,0.0,USD,5.8M,...,False,False,Medical Assistant Degree Medical Assistant Job...,7.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656450e+18,1.1.4,Free
4,Business Administration,Education,4.023256,86.0,"50,000+",50000.0,True,0.0,USD,5.7M,...,False,False,"Business Administration Learning, Business Adm...",29.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656450e+18,1.1.6,Free

In [36]:
df=df.drop(columns=['Free'])

In [37]:
df.head()

,App Name,Category,Rating,Rating Count,Installs,Minimum Installs,Price,Currency,Size,Minimum Android,...,In app purchases,Editor Choice,Summary,Reviews,Android version Text,Developer,Developer Address,Developer Internal ID,Version,App Type
0,Logistics Management,Education,4.090909,66.0,"10,000+",10000.0,0.0,USD,5.8M,4,...,False,False,Leading Online Learning and Training System in...,28.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656450e+18,1.1.5,Free
1,Estados Unidos Noticias,News & Magazines,4.000000,8.0,"1,000+",1000.0,0.0,USD,5.3M,4,...,False,False,Top Stories\r\nWorld\r\nEntertainment\r\nSport...,3.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656450e+18,1.2.3,Free
2,Dental Assistant,Education,3.866667,15.0,"10,000+",10000.0,0.0,USD,5.7M,4,...,False,False,"Dental Assistant: Study Dental Assistant, Dent...",3.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656450e+18,1.1.5,Free
3,Medical Assistant,Education,4.000000,18.0,"5,000+",5000.0,0.0,USD,5.8M,4,...,False,False,Medical Assistant Degree Medical Assistant Job...,7.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656450e+18,1.1.4,Free
4,Business Administration,Education,4.023256,86.0,"50,000+",50000.0,0.0,USD,5.7M,4,...,False,False,"Business Administration Learning, Business Adm...",29.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656450e+18,1.1.6,Free

In [38]:
df['Rating']

0         4.090909
1         4.000000
2         3.866667
3         4.000000
4         4.023256
            ...
450790    4.240000
450791    2.961539
450792    3.500000
450793         NaN
450794    2.860000
Name: Rating, Length: 450703, dtype: float64

In [39]:
df['Rating']=pd.to_numeric(df['Rating'],errors='coerce')
df['Rating']=df['Rating'].round(1)

In [40]:
df['Rating'].unique()

array([4.1, 4. , 3.9, 2.4, 0. , 4.3, 4.7, 4.4, 4.6, 5. , 4.2, 2.5, 3.6,
       3.1, 3.8, 3.4, 3.7, 3.5, 4.5, 4.8, 4.9, 3.3, 2.8, 2.7, nan, 3.2,
       2. , 3. , 2.6, 2.2, 1.6, 2.9, 2.3, 2.1, 1.5, 1.8, 1.4, 1.1, 1.7,
       1.9, 1.2, 1.3, 1. ])

In [41]:
df['Rating'].isnull().sum()

np.int64(2720)

In [42]:
df['Rating'].isnull().mean()*100

np.float64(0.6035016407700858)

In [43]:
# value 0-5 k under ho to mean , median
df["Rating"]=df["Rating"].fillna(df['Rating'].median())

In [44]:
df['Rating'].unique()

array([4.1, 4. , 3.9, 2.4, 0. , 4.3, 4.7, 4.4, 4.6, 5. , 4.2, 2.5, 3.6,
       3.1, 3.8, 3.4, 3.7, 3.5, 4.5, 4.8, 4.9, 3.3, 2.8, 2.7, 3.2, 2. ,
       3. , 2.6, 2.2, 1.6, 2.9, 2.3, 2.1, 1.5, 1.8, 1.4, 1.1, 1.7, 1.9,
       1.2, 1.3, 1. ])

In [45]:
df['Rating']

0         4.1
1         4.0
2         3.9
3         4.0
4         4.0
         ...
450790    4.2
450791    3.0
450792    3.5
450793    3.9
450794    2.9
Name: Rating, Length: 450703, dtype: float64

In [46]:
df['Rating Count'].value_counts()

Rating Count
5.0         8837
6.0         7705
7.0         6726
8.0         6015
9.0         5529
            ...
12473.0        1
11723.0        1
5047.0         1
33303.0        1
152307.0       1
Name: count, Length: 32695, dtype: int64

In [47]:
df['Rating Count'].unique()

array([6.6000e+01, 8.0000e+00, 1.5000e+01, ..., 2.3355e+04, 3.0305e+04,
       5.3562e+04])

In [48]:
df['Rating Count']=pd.to_numeric(df['Rating Count'],errors='coerce')
df['Rating Count']=df['Rating Count'].round(1)

In [49]:
df['Rating Count'].unique()

array([6.6000e+01, 8.0000e+00, 1.5000e+01, ..., 2.3355e+04, 3.0305e+04,
       5.3562e+04])

In [50]:
df['Rating Count'].isnull().sum()

np.int64(118676)

In [51]:
df['Rating Count'].isnull().mean()*100

np.float64(26.331309088246584)

In [52]:
df['Rating Count'] = df['Rating Count'].fillna(
    df['Rating Count'].median()
)

In [53]:
df['Rating Count'].value_counts()

Rating Count
123.0       119050
5.0           8837
6.0           7705
7.0           6726
8.0           6015
             ...
12473.0          1
11723.0          1
5047.0           1
33303.0          1
152307.0         1
Name: count, Length: 32695, dtype: int64

In [54]:
df[['Installs']]

        Installs
0        10,000+
1         1,000+
2        10,000+
3         5,000+
4        50,000+
...          ...
450790  100,000+
450791   10,000+
450792   10,000+
450793    5,000+
450794   10,000+

[450703 rows x 1 columns]

In [55]:
type('Installs')

str

In [56]:
df['Installs'].head()

0    10,000+
1     1,000+
2    10,000+
3     5,000+
4    50,000+
Name: Installs, dtype: object

In [57]:
df.columns

Index(['App Name', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Price', 'Currency', 'Size', 'Minimum Android',
       'Developer Id', 'Developer Website', 'Developer Email', 'Released',
       'Last update', 'Privacy Policy', 'Content Rating', 'Ad Supported',
       'In app purchases', 'Editor Choice', 'Summary', 'Reviews',
       'Android version Text', 'Developer', 'Developer Address',
       'Developer Internal ID', 'Version', 'App Type'],
      dtype='object')

In [58]:
# replace +
df["Installs"]=df["Installs"].str.replace("+","")

In [59]:
df["Installs"].unique()

array(['10,000', '1,000', '5,000', '50,000', '100,000', '10', '500,000',
       '1,000,000', '5', '100', '0', '500', '10,000,000', '5,000,000',
       '500,000,000', '50,000,000', '50', '100,000,000', '1',
       '1,000,000,000', '5,000,000,000', '10,000,000,000'], dtype=object)

In [60]:
df["Installs"].head()

0    10,000
1     1,000
2    10,000
3     5,000
4    50,000
Name: Installs, dtype: object

In [61]:
# replace ,
df["Installs"]=df["Installs"].str.replace("," , "")

In [62]:
df["Installs"].head()

0    10000
1     1000
2    10000
3     5000
4    50000
Name: Installs, dtype: object

In [63]:
df["Installs"].unique()

array(['10000', '1000', '5000', '50000', '100000', '10', '500000',
       '1000000', '5', '100', '0', '500', '10000000', '5000000',
       '500000000', '50000000', '50', '100000000', '1', '1000000000',
       '5000000000', '10000000000'], dtype=object)

In [64]:
df["Installs"].isnull().sum()

np.int64(0)

In [65]:
df['Installs'].isnull().mean()* 100

np.float64(0.0)

In [66]:
# nan value kam thi so use zero  se replace kiya
df["Installs"].fillna(0,inplace=True)

/tmp/ipykernel_6015/2554501345.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Installs"].fillna(0,inplace=True)

In [67]:
# datatype object to int convert
df["Installs"] = df["Installs"].astype(int)

In [68]:
df["Installs"].info()

<class 'pandas.core.series.Series'>
Index: 450703 entries, 0 to 450794
Series name: Installs
Non-Null Count   Dtype
--------------   -----
450703 non-null  int64
dtypes: int64(1)
memory usage: 6.9 MB

In [69]:
df["Installs"].value_counts()

Installs
10000          78204
1000           74113
100000         52424
100            51972
5000           34420
50000          29550
500            27589
10             23378
1000000        23056
500000         15927
50             15874
10000000        5412
5000000         5325
5               5232
1               5136
0               1601
50000000         816
100000000        530
500000000         64
1000000000        63
5000000000        16
10000000000        1
Name: count, dtype: int64

In [70]:
df["Installs"].describe()

count    4.507030e+05
mean     8.838031e+05
std      3.607942e+07
min      0.000000e+00
25%      5.000000e+02
50%      5.000000e+03
75%      5.000000e+04
max      1.000000e+10
Name: Installs, dtype: float64

In [71]:
type(df["Installs"])

pandas.core.series.Series

In [72]:
df['Rating Count'].describe()

count    4.507030e+05
mean     1.434565e+04
std      5.702269e+05
min      3.000000e+00
25%      4.300000e+01
50%      1.230000e+02
75%      4.260000e+02
max      1.386210e+08
Name: Rating Count, dtype: float64

In [73]:
df.groupby('Rating Count')['Rating'].max()

Rating Count
3.0            3.7
4.0            3.7
5.0            5.0
6.0            5.0
7.0            5.0
              ...
117876494.0    2.3
120260139.0    3.8
120270877.0    3.8
138611377.0    4.0
138620959.0    4.0
Name: Rating, Length: 32695, dtype: float64

In [74]:
df.columns

Index(['App Name', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Price', 'Currency', 'Size', 'Minimum Android',
       'Developer Id', 'Developer Website', 'Developer Email', 'Released',
       'Last update', 'Privacy Policy', 'Content Rating', 'Ad Supported',
       'In app purchases', 'Editor Choice', 'Summary', 'Reviews',
       'Android version Text', 'Developer', 'Developer Address',
       'Developer Internal ID', 'Version', 'App Type'],
      dtype='object')

In [75]:
df['Minimum Installs'].describe()

count    4.507030e+05
mean     8.838031e+05
std      3.607942e+07
min      0.000000e+00
25%      5.000000e+02
50%      5.000000e+03
75%      5.000000e+04
max      1.000000e+10
Name: Minimum Installs, dtype: float64

In [76]:
df['Minimum Installs'].unique()

array([1.e+04, 1.e+03, 5.e+03, 5.e+04, 1.e+05, 1.e+01, 5.e+05, 1.e+06,
       5.e+00, 1.e+02, 0.e+00, 5.e+02, 1.e+07, 5.e+06, 5.e+08, 5.e+07,
       5.e+01, 1.e+08, 1.e+00, 1.e+09, 5.e+09, 1.e+10])

In [77]:
#change formate for displat to actual value
pd.set_option('display.float_format','{:,.0f}'.format)

In [78]:
df['Minimum Installs']

0         10,000
1          1,000
2         10,000
3          5,000
4         50,000
           ...
450790   100,000
450791    10,000
450792    10,000
450793     5,000
450794    10,000
Name: Minimum Installs, Length: 450703, dtype: float64

In [79]:
df['Minimum Installs'].isnull().sum()

np.int64(0)

In [80]:
df['Minimum Installs'].isnull().mean().sum()*100

np.float64(0.0)

In [81]:
df['Minimum Installs']=df['Minimum Installs'].replace(np.nan,0)

In [82]:
df['Minimum Installs'].isnull().sum()

np.int64(0)

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 450703 entries, 0 to 450794
Data columns (total 28 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   App Name               450703 non-null  object
 1   Category               450703 non-null  object
 2   Rating                 450703 non-null  float64
 3   Rating Count           450703 non-null  float64
 4   Installs               450703 non-null  int64
 5   Minimum Installs       450703 non-null  float64
 6   Price                  450703 non-null  float64
 7   Currency               450703 non-null  object
 8   Size                   450689 non-null  object
 9   Minimum Android        449634 non-null  object
 10  Developer Id           450700 non-null  object
 11  Developer Website      341010 non-null  object
 12  Developer Email        450690 non-null  object
 13  Released               447347 non-null  object
 14  Last update            450703 non-null  object
 15  Privacy Policy         399880 non-null  object
 16  Content Rating         450703 non-null  object
 17  Ad Supported           281019 non-null  object
 18  In app purchases       450703 non-null  bool
 19  Editor Choice          450703 non-null  bool
 20  Summary                450515 non-null  object
 21  Reviews                447983 non-null  float64
 22  Android version Text   449634 non-null  object
 23  Developer              450700 non-null  object
 24  Developer Address      261927 non-null  object
 25  Developer Internal ID  450703 non-null  float64
 26  Version                450543 non-null  object
 27  App Type               450703 non-null  object
dtypes: bool(2), float64(6), int64(1), object(19)
memory usage: 93.7+ MB

In [226]:
# df['Free'].value_counts()

In [87]:
# df['Free'].unique()

In [ ]:
#df['Free']=df['Free'].replace(True,1)

In [ ]:
#df['Free']=df['Free'].replace(False,0)

In [ ]:
# df['Free'].fillna(0,inplace=True)

In [88]:
df['Currency'].head()

0    USD
1    USD
2    USD
3    USD
4    USD
Name: Currency, dtype: object

In [89]:
df['Currency'].isnull().sum()

np.int64(0)

In [90]:
df['Currency'].value_counts()

Currency
USD    428344
XXX     21867
EUR       101
INR        43
GBP        32
PKR        30
THB        27
HKD        22
TRY        21
RUB        21
VND        16
BDT        14
BGN        14
KRW        13
CAD        12
IDR        12
UAH        12
AUD        10
SGD         9
JPY         8
RSD         7
ZAR         6
PLN         5
ILS         5
PEN         5
CHF         5
BRL         4
AED         4
DKK         4
KES         3
CZK         3
NGN         3
MYR         2
TWD         2
SEK         2
MXN         2
NZD         2
EGP         2
GHS         1
TZS         1
COP         1
LBP         1
DZD         1
KZT         1
HUF         1
LKR         1
BOB         1
Name: count, dtype: int64

In [91]:
mode_value = df['Currency'].mode()[0]
df['Currency'] = df['Currency'].fillna(mode_value)

In [92]:
df['Currency'].head()

0    USD
1    USD
2    USD
3    USD
4    USD
Name: Currency, dtype: object

In [93]:
df.head()

,App Name,Category,Rating,Rating Count,Installs,Minimum Installs,Price,Currency,Size,Minimum Android,...,In app purchases,Editor Choice,Summary,Reviews,Android version Text,Developer,Developer Address,Developer Internal ID,Version,App Type
0,Logistics Management,Education,4,66,10000,"10,000",0,USD,5.8M,4,...,False,False,Leading Online Learning and Training System in...,28,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...","4,656,450,000,000,000,000",1.1.5,Free
1,Estados Unidos Noticias,News & Magazines,4,8,1000,"1,000",0,USD,5.3M,4,...,False,False,Top Stories\r\nWorld\r\nEntertainment\r\nSport...,3,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...","4,656,450,000,000,000,000",1.2.3,Free
2,Dental Assistant,Education,4,15,10000,"10,000",0,USD,5.7M,4,...,False,False,"Dental Assistant: Study Dental Assistant, Dent...",3,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...","4,656,450,000,000,000,000",1.1.5,Free
3,Medical Assistant,Education,4,18,5000,"5,000",0,USD,5.8M,4,...,False,False,Medical Assistant Degree Medical Assistant Job...,7,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...","4,656,450,000,000,000,000",1.1.4,Free
4,Business Administration,Education,4,86,50000,"50,000",0,USD,5.7M,4,...,False,False,"Business Administration Learning, Business Adm...",29,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...","4,656,450,000,000,000,000",1.1.6,Free

In [94]:
df['Currency'].unique()

array(['USD', 'XXX', 'INR', 'SGD', 'MYR', 'GBP', 'TRY', 'EUR', 'ILS',
       'VND', 'PKR', 'KRW', 'PLN', 'HKD', 'PEN', 'AED', 'IDR', 'UAH',
       'DKK', 'RUB', 'CZK', 'CAD', 'BGN', 'JPY', 'RSD', 'SEK', 'BRL',
       'THB', 'GHS', 'AUD', 'ZAR', 'BDT', 'NGN', 'COP', 'EGP', 'NZD',
       'TZS', 'TWD', 'KES', 'MXN', 'LBP', 'DZD', 'CHF', 'KZT', 'HUF',
       'LKR', 'BOB'], dtype=object)

In [95]:
df['Currency'] = df['Currency'].replace('XXX','Others')

In [96]:
df['Currency'].unique()

array(['USD', 'Others', 'INR', 'SGD', 'MYR', 'GBP', 'TRY', 'EUR', 'ILS',
       'VND', 'PKR', 'KRW', 'PLN', 'HKD', 'PEN', 'AED', 'IDR', 'UAH',
       'DKK', 'RUB', 'CZK', 'CAD', 'BGN', 'JPY', 'RSD', 'SEK', 'BRL',
       'THB', 'GHS', 'AUD', 'ZAR', 'BDT', 'NGN', 'COP', 'EGP', 'NZD',
       'TZS', 'TWD', 'KES', 'MXN', 'LBP', 'DZD', 'CHF', 'KZT', 'HUF',
       'LKR', 'BOB'], dtype=object)

In [97]:
df['Currency'].isnull().sum()

np.int64(0)

In [98]:
df['Size'].head()

0    5.8M
1    5.3M
2    5.7M
3    5.8M
4    5.7M
Name: Size, dtype: object

In [99]:
df['Size'].unique()

array(['5.8M', '5.3M', '5.7M', ..., '801k', '332M', '6.8k'], dtype=object)

In [100]:
df['Size'].value_counts()

Size
Varies with device    21594
11M                   11278
12M                   10231
13M                    9296
14M                    8604
                      ...
314M                      1
639k                      1
801k                      1
332M                      1
6.8k                      1
Name: count, Length: 1530, dtype: int64

In [101]:
# diffrent size to one size(kb) convert
def convert_size(x):
    x = str(x).strip().upper()
    x = x.replace(',','')

    if x.endswith('K'):
        return float(x[:-1])

    elif x.endswith('M'):
        return float(x[:-1]) * 1024

    elif x.endswith('G'):
        return float(x[:-1]) * 1024 * 1024

    else:
        return np.nan

df['Size'] = df['Size'].apply(convert_size)

In [102]:
df['Size'].head()

0   5,939
1   5,427
2   5,837
3   5,939
4   5,837
Name: Size, dtype: float64

In [103]:
type(df['Size'])

pandas.core.series.Series

In [104]:
df['Size'].head()

0   5,939
1   5,427
2   5,837
3   5,939
4   5,837
Name: Size, dtype: float64

In [105]:
df.columns

Index(['App Name', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Price', 'Currency', 'Size', 'Minimum Android',
       'Developer Id', 'Developer Website', 'Developer Email', 'Released',
       'Last update', 'Privacy Policy', 'Content Rating', 'Ad Supported',
       'In app purchases', 'Editor Choice', 'Summary', 'Reviews',
       'Android version Text', 'Developer', 'Developer Address',
       'Developer Internal ID', 'Version', 'App Type'],
      dtype='object')

In [106]:
df['Minimum Android'].unique()

array(['4', '4.1', '5', '4.4', '6', '2.3', '4.2', 'Varies', '7', '4.3',
       '4.0.3', '5.1', '2.2', '2.3.3', '1.6', '2.1', '4.4W', '3', nan,
       '8', '7.1', '3.1', '3.2', '1.1', '1.5', '2.0.1', '2', '1'],
      dtype=object)

In [107]:
# replace W into empty ''
df['Minimum Android']=df['Minimum Android'].str.replace('W','')

In [108]:
df['Minimum Android'].str.endswith('W').value_counts()

Minimum Android
False    449634
Name: count, dtype: int64

In [109]:
# replace varies to nan value
df['Minimum Android']=df['Minimum Android'].replace('Varies', np.nan)

In [110]:
# convert into float numbers
df['Minimum Android'] = pd.to_numeric(
    df['Minimum Android'],
    errors='coerce'
)

In [111]:
type(df['Minimum Android'])

pandas.core.series.Series

In [112]:
df['Minimum Android'].unique()

array([4. , 4.1, 5. , 4.4, 6. , 2.3, 4.2, nan, 7. , 4.3, 5.1, 2.2, 1.6,
       2.1, 3. , 8. , 7.1, 3.1, 3.2, 1.1, 1.5, 2. , 1. ])

In [113]:
# bohot jyada missing value hain so isko handle karna padega
df['Minimum Android'].isna().sum()

np.int64(49868)

In [114]:
# agr iski value 5-10 k around hoti to mean or median se fill sakte the
df['Minimum Android'].isna().mean() * 100

np.float64(11.064492581589207)

In [115]:
# 10+ percentage aya isi liye mode pa use kiya
mode_value = df['Minimum Android'].mode()[0]

df['Minimum Android'] = df['Minimum Android'].fillna(mode_value)

In [116]:
df['Minimum Android'].unique()

array([4. , 4.1, 5. , 4.4, 6. , 2.3, 4.2, 7. , 4.3, 5.1, 2.2, 1.6, 2.1,
       3. , 8. , 7.1, 3.1, 3.2, 1.1, 1.5, 2. , 1. ])

In [117]:
df['Developer Id'].unique()

array(['4.65645e+18', '7.41545e+18', '8.00375e+18', ...,
       'MPOnline+Limited', 'X.X_Mass_Developer', 'wholesale7'],
      dtype=object)

In [118]:
df['Developer Id']=df['Developer Id'].astype('string')

In [119]:
df['Developer Id'].isnull().sum()

np.int64(3)

In [120]:
df['Developer Id'].isnull().mean()*100

np.float64(0.0006656268096728888)

In [121]:
df = df.drop(columns=['Developer Id'])

In [122]:
df.columns

Index(['App Name', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Price', 'Currency', 'Size', 'Minimum Android',
       'Developer Website', 'Developer Email', 'Released', 'Last update',
       'Privacy Policy', 'Content Rating', 'Ad Supported', 'In app purchases',
       'Editor Choice', 'Summary', 'Reviews', 'Android version Text',
       'Developer', 'Developer Address', 'Developer Internal ID', 'Version',
       'App Type'],
      dtype='object')

In [123]:
df['Developer Website'].unique()

array([nan, 'https://blank-b131c.firebaseapp.com/',
       'https://blank-b131c.firebaseapp.com', ...,
       'http://www.rautsikapps.com/',
       'http://appads.upearn.xyz/app-ads.txt', 'http://m.wholesale7.net'],
      dtype=object)

In [124]:
df['Developer Website'].isnull().sum()

np.int64(109693)

In [125]:
df['Developer Website'].isnull().mean().sum()*100

np.float64(24.33820054448273)

In [126]:
df = df.drop(columns=['Developer Website'])

In [127]:
df.columns

Index(['App Name', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Price', 'Currency', 'Size', 'Minimum Android',
       'Developer Email', 'Released', 'Last update', 'Privacy Policy',
       'Content Rating', 'Ad Supported', 'In app purchases', 'Editor Choice',
       'Summary', 'Reviews', 'Android version Text', 'Developer',
       'Developer Address', 'Developer Internal ID', 'Version', 'App Type'],
      dtype='object')

In [128]:
df['Developer Email'].unique()

array(['eniseistudio@gmail.com', 'rishabh.cse12@gmail.com',
       'orvalwekawulusanyub@gmail.com', ...,
       'dhiraj.chouksey@mponline.gov.in', 'philjay.librarysup@gmail.com',
       'tec@wholesale7.net'], dtype=object)

In [129]:
df['Developer Email'].isnull().sum()

np.int64(13)

In [130]:
df['Developer Email'].isnull().mean()*100

np.float64(0.0028843828419158517)

In [131]:
df = df.drop(columns=['Developer Email'])

In [132]:
df['Released'].unique()

array(['Jul 19, 2017', 'May 5, 2017', 'Jul 18, 2017', ..., 'Jun 10, 2010',
       'May 21, 2010', 'Jun 15, 2021'], dtype=object)

In [133]:
df['Released'].value_counts().head(3)

Released
Jul 31, 2019    382
May 19, 2020    380
Jun 16, 2020    378
Name: count, dtype: int64

In [134]:
df['Released'].isnull().sum()

np.int64(3356)

In [135]:
df['Released'].isnull().mean()*100

np.float64(0.7446145244207383)

In [136]:
df['Released']=df['Released'].fillna('Not available')

In [137]:
df['Released'].head(3)

0    Jul 19, 2017
1     May 5, 2017
2    Jul 18, 2017
Name: Released, dtype: object

In [138]:
df['Released'].isnull().sum()

np.int64(0)

In [139]:
df.columns

Index(['App Name', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Price', 'Currency', 'Size', 'Minimum Android',
       'Released', 'Last update', 'Privacy Policy', 'Content Rating',
       'Ad Supported', 'In app purchases', 'Editor Choice', 'Summary',
       'Reviews', 'Android version Text', 'Developer', 'Developer Address',
       'Developer Internal ID', 'Version', 'App Type'],
      dtype='object')

In [140]:
df['Last update'].unique()

array(['July 19, 2017', 'May 5, 2017', 'July 18, 2017', ...,
       'June 4, 2010', 'October 20, 2011', 'April 3, 2012'], dtype=object)

In [141]:
df['Last update'].value_counts().head()

Last update
May 27, 2021    2474
May 28, 2021    2391
May 21, 2021    2173
May 26, 2021    2166
May 25, 2021    2153
Name: count, dtype: int64

In [142]:
df['Last update'] = pd.to_datetime(df['Last update'], errors='coerce')

In [143]:
df['Last update'].isnull().sum()

np.int64(12084)

In [144]:
df['Last update'].isnull().mean()*100

np.float64(2.681144789362396)

In [145]:
df=df.dropna(subset=['Last update'])

In [146]:
df['Privacy Policy'].unique()

array([nan, 'https://sites.google.com/view/earlylearninggame/home',
       'https://sites.google.com/view/desertrunnerboy', ...,
       'https://www.mponline.gov.in/Portal/policy.aspx',
       'https://sites.google.com/view/rautsik/ir-remote-control',
       'https://m.wholesale7.net/vue/#/articleDetail/1057'], dtype=object)

In [147]:
df['Privacy Policy'].isnull().sum()

np.int64(49480)

In [148]:
df['Privacy Policy'].isnull().mean()*100

np.float64(11.280861066210083)

In [149]:
df = df.drop(columns=['Privacy Policy'])

In [150]:
df['Content Rating'].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+', 'Unrated',
       'Adults only 18+'], dtype=object)

In [151]:
df['Content Rating'].value_counts()

Content Rating
Everyone           374924
Teen                40090
Mature 17+          13230
Everyone 10+        10333
Adults only 18+        29
Unrated                13
Name: count, dtype: int64

In [152]:
df['Content Rating'].isnull().sum()

np.int64(0)

In [153]:
df['Ad Supported'].unique()

array([True, nan], dtype=object)

In [154]:
df['Ad Supported'].isnull().sum()

np.int64(162473)

In [155]:
df['Ad Supported'].isnull().mean()*100

np.float64(37.04194300748485)

In [156]:
df['Ad Supported']=df['Ad Supported'].fillna('Not Available')

In [157]:
df['Ad Supported'].value_counts()

Ad Supported
True             276146
Not Available    162473
Name: count, dtype: int64

In [158]:
df.columns

Index(['App Name', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Price', 'Currency', 'Size', 'Minimum Android',
       'Released', 'Last update', 'Content Rating', 'Ad Supported',
       'In app purchases', 'Editor Choice', 'Summary', 'Reviews',
       'Android version Text', 'Developer', 'Developer Address',
       'Developer Internal ID', 'Version', 'App Type'],
      dtype='object')

In [159]:
df['In app purchases'].unique()

array([False,  True])

In [160]:
df['In app purchases'].isnull().sum()

np.int64(0)

In [161]:
df['In app purchases'].value_counts()

In app purchases
False    350920
True      87699
Name: count, dtype: int64

In [162]:
df.head()

,App Name,Category,Rating,Rating Count,Installs,Minimum Installs,Price,Currency,Size,Minimum Android,...,In app purchases,Editor Choice,Summary,Reviews,Android version Text,Developer,Developer Address,Developer Internal ID,Version,App Type
0,Logistics Management,Education,4,66,10000,"10,000",0,USD,"5,939",4,...,False,False,Leading Online Learning and Training System in...,28,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...","4,656,450,000,000,000,000",1.1.5,Free
1,Estados Unidos Noticias,News & Magazines,4,8,1000,"1,000",0,USD,"5,427",4,...,False,False,Top Stories\r\nWorld\r\nEntertainment\r\nSport...,3,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...","4,656,450,000,000,000,000",1.2.3,Free
2,Dental Assistant,Education,4,15,10000,"10,000",0,USD,"5,837",4,...,False,False,"Dental Assistant: Study Dental Assistant, Dent...",3,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...","4,656,450,000,000,000,000",1.1.5,Free
3,Medical Assistant,Education,4,18,5000,"5,000",0,USD,"5,939",4,...,False,False,Medical Assistant Degree Medical Assistant Job...,7,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...","4,656,450,000,000,000,000",1.1.4,Free
4,Business Administration,Education,4,86,50000,"50,000",0,USD,"5,837",4,...,False,False,"Business Administration Learning, Business Adm...",29,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...","4,656,450,000,000,000,000",1.1.6,Free

In [163]:
df['Editor Choice'].unique()

array([False,  True])

In [164]:
df['Summary'].unique()

array(['Leading Online Learning and Training System in Logistics Management',
       'Top Stories\r\nWorld\r\nEntertainment\r\nSport\r\nTravel\r\nTechnology\r\nHealth\r\nBusiness\r\nPhotos',
       'Dental Assistant: Study Dental Assistant, Dental Assistant Training Courses.',
       ..., 'Learn how to make money from home',
       'A new debit card that lets you and your partner split, set and forget!',
       'Wholesale7 is an affordable online wholesale website in China'],
      dtype=object)

In [165]:
df['Summary'].isnull().sum()

np.int64(184)

In [166]:
df['Summary'].isnull().mean()*100

np.float64(0.04194984713384509)

In [167]:
df = df.drop(columns=['Summary'])

In [168]:
df['Reviews'].unique()

array([2.8000e+01, 3.0000e+00, 7.0000e+00, ..., 1.2754e+04, 1.2579e+04,
       7.7640e+03])

In [169]:
df['Reviews'].isnull().sum()

np.int64(2647)

In [170]:
df['Reviews'].isnull().mean()*100

np.float64(0.6034850291483042)

In [171]:
df['Reviews']=df['Reviews'].fillna('Not available')

In [172]:
df['Reviews']

0                    28
1                     3
2                     3
3                     7
4                    29
              ...
450790              257
450791               26
450792               41
450793    Not available
450794               80
Name: Reviews, Length: 438619, dtype: object

In [173]:
df['Android version Text'].unique()

array(['4.0 and up', '4.1 and up', '5.0 and up', '4.4 and up',
       '6.0 and up', '2.3 and up', '4.2 and up', 'Varies with device',
       '7.0 and up', '4.3 and up', '4.0.3 and up', '5.1 and up',
       '2.2 and up', '2.3.3 and up', '1.6 and up', '2.1 and up',
       '4.4W and up', '3.0 and up', nan, '8.0 and up', '7.1 and up',
       '4.1 - 7.1.1', '3.1 and up', '3.2 and up', '1.1 and up',
       '1.5 and up', '2.0.1 and up', '2.0 and up', '6.0 - 7.1.1',
       '1.0 and up', '4.0 - 6.0', '2.3 - 4.4', '4.2 - 7.1.1', '4.0 - 8.0',
       '4.1 - 4.4', '2.3 - 7.0', '4.4 - 6.0', '4.0 - 4.4', '4.1 - 5.1',
       '4.2 - 6.0', '7', '2.2 - 4.0.4', '4.2 - 8.0', '4.1 - 6.0', '4.4',
       '4.1 - 7.0', '4.3 - 4.4W', '2.3 - 4.4W', '4.1 - 8.0', '5.0 - 8.0',
       '5.0 - 6.0', '2.2 - 4.3', '8', '2.1 - 5.0', '4.1 - 4.3',
       '1.5 - 2.1', '2.3 - 5.1', '4.0.3 - 8.0', '3.0 - 5.0', '4.0 - 4.4W',
       '4.0.3 - 7.1.1', '2.2', '4.4 - 7.1.1', '2.2 - 3.2', '2.3 - 4.0.2',
       '2.1 - 4.4', '2.3 - 3.2', '2.3 - 7.1.1', '2.3 - 5.0', '4.0 - 5.0',
       '2.3.3 - 4.3', '2.3.3 - 4.4', '4.4 - 7.0', '4.0 - 5.1',
       '2.3 - 6.0', '3.0 - 6.0', '3.0 - 4.1.1'], dtype=object)

In [174]:
df['Android version Text'].isnull().sum()

np.int64(1039)

In [175]:
df['Android version Text'].isnull().mean()*100

np.float64(0.2368798433264405)

In [176]:
df = df.drop(columns=['Android version Text'])

In [177]:
df.columns

Index(['App Name', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Price', 'Currency', 'Size', 'Minimum Android',
       'Released', 'Last update', 'Content Rating', 'Ad Supported',
       'In app purchases', 'Editor Choice', 'Reviews', 'Developer',
       'Developer Address', 'Developer Internal ID', 'Version', 'App Type'],
      dtype='object')

In [178]:
df['Developer'].unique()

array(['eniseistudio', 'Early Learn', 'TUTORIFY', ..., 'MPOnline Limited',
       'X.X_Mass_Developer', 'wholesale7'], dtype=object)

In [179]:
df['Developer'].isnull().sum()

np.int64(3)

In [180]:
df['Developer Address'].unique()

array(['7115 N Muscatel Ave San Gabriel, CA 91775 United States', 'CA',
       'East Java', ...,
       '104 å\x8f°åŒ—å¸‚ä¸\xadå±±å\x8d€æ\x9d¾æ±Ÿè·¯101è™Ÿ12æ¨“',
       'Estonia, Tallinn, Kesklinn, R. Tobiase 9, 10152',
       'Russian Federation, Tyumen, Muravlenko 9'], dtype=object)

In [181]:
df['Developer Address'].isnull().sum()

np.int64(184533)

In [182]:
df.drop('Developer Address', axis=1, inplace=True)

In [183]:
df['Developer Internal ID'].unique()

array([4.65645e+18, 7.41545e+18, 8.00375e+18, ..., 5.44924e+18,
       7.16624e+18, 7.64987e+18])

In [184]:
df = df.drop(columns=['Developer Internal ID'])

In [185]:
df['Version'].unique()

array(['1.1.5', '1.2.3', '1.1.4', ..., 'Build 1.28', 'Build 1.0.8',
       'Build 1.0.4'], dtype=object)

In [186]:
df = df.drop(columns=['Version'])

In [187]:
df.columns

Index(['App Name', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Price', 'Currency', 'Size', 'Minimum Android',
       'Released', 'Last update', 'Content Rating', 'Ad Supported',
       'In app purchases', 'Editor Choice', 'Reviews', 'Developer',
       'App Type'],
      dtype='object')

In [188]:
df[['Rating', 'Rating Count', 'Installs', 'Minimum Installs']].corr()

                  Rating  Rating Count  Installs  Minimum Installs
Rating                 1             0         0                 0
Rating Count           0             1         1                 1
Installs               0             1         1                 1
Minimum Installs       0             1         1                 1

In [189]:
df[['Installs','Minimum Installs']].corr()

                  Installs  Minimum Installs
Installs                 1                 1
Minimum Installs         1                 1

In [190]:
#install and minimum install kafi hak same hain so
df = df.drop(columns=['Minimum Installs'])

In [191]:
df.columns

Index(['App Name', 'Category', 'Rating', 'Rating Count', 'Installs', 'Price',
       'Currency', 'Size', 'Minimum Android', 'Released', 'Last update',
       'Content Rating', 'Ad Supported', 'In app purchases', 'Editor Choice',
       'Reviews', 'Developer', 'App Type'],
      dtype='object')

In [192]:
df.shape

(438619, 18)

In [193]:
df.head()

,App Name,Category,Rating,Rating Count,Installs,Price,Currency,Size,Minimum Android,Released,Last update,Content Rating,Ad Supported,In app purchases,Editor Choice,Reviews,Developer,App Type
0,Logistics Management,Education,4,66,10000,0,USD,"5,939",4,"Jul 19, 2017",2017-07-19,Everyone,True,False,False,28,eniseistudio,Free
1,Estados Unidos Noticias,News & Magazines,4,8,1000,0,USD,"5,427",4,"May 5, 2017",2017-05-05,Everyone,True,False,False,3,eniseistudio,Free
2,Dental Assistant,Education,4,15,10000,0,USD,"5,837",4,"Jul 18, 2017",2017-07-18,Everyone,True,False,False,3,eniseistudio,Free
3,Medical Assistant,Education,4,18,5000,0,USD,"5,939",4,"Jun 24, 2017",2017-06-24,Everyone,True,False,False,7,eniseistudio,Free
4,Business Administration,Education,4,86,50000,0,USD,"5,837",4,"Jun 13, 2017",2017-10-06,Everyone,True,False,False,29,eniseistudio,Free

In [194]:
df['Category'].value_counts()

Category
Education                  45660
Tools                      33191
Personalization            29288
Books & Reference          29002
Music & Audio              27879
Entertainment              21648
Lifestyle                  18317
Business                   15945
Productivity               14360
Health & Fitness           13773
Puzzle                     13348
Travel & Local             11927
Casual                     10417
Photography                10408
Sports                      9820
Finance                     8918
Simulation                  8676
News & Magazines            8083
Arcade                      7993
Shopping                    7559
Food & Drink                7553
Communication               6944
Action                      6333
Educational                 6032
Social                      5658
Medical                     5090
Adventure                   5058
Maps & Navigation           4680
Video Players & Editors     4267
Role Playing                4221
Art & Design                3617
Racing                      3397
Board                       3029
Strategy                    2805
Word                        2742
Card                        2732
Auto & Vehicles             2646
Weather                     2300
Trivia                      2245
House & Home                1952
Beauty                      1746
Casino                      1246
Dating                      1225
Libraries & Demo            1183
Events                      1166
Music                       1016
Parenting                    822
Comics                       702
Name: count, dtype: int64

In [195]:
category_groups = {
    'Education & Learning': ['Education', 'Educational', 'Books & Reference'],

    'Music & Audio': [ 'Music', 'Music & Audio'],

    'Entertainment & Media': ['Entertainment', 'Video Players & Editors'],

    'Travel & Navigation': ['Travel & Local', 'Maps & Navigation'],

    'Business & Productivity': ['Business', 'Productivity'],

    'Social & Communication': ['Social', 'Communication', 'Dating']
}

df['Category_Group'] = df['Category']

for group, categories in category_groups.items():
    df.loc[df['Category'].isin(categories),
           'Category_Group'] = group

In [196]:
df['Category']=df['Category_Group']

In [197]:
df = df.drop(columns='Category_Group')

In [198]:
df.head()

,App Name,Category,Rating,Rating Count,Installs,Price,Currency,Size,Minimum Android,Released,Last update,Content Rating,Ad Supported,In app purchases,Editor Choice,Reviews,Developer,App Type
0,Logistics Management,Education & Learning,4,66,10000,0,USD,"5,939",4,"Jul 19, 2017",2017-07-19,Everyone,True,False,False,28,eniseistudio,Free
1,Estados Unidos Noticias,News & Magazines,4,8,1000,0,USD,"5,427",4,"May 5, 2017",2017-05-05,Everyone,True,False,False,3,eniseistudio,Free
2,Dental Assistant,Education & Learning,4,15,10000,0,USD,"5,837",4,"Jul 18, 2017",2017-07-18,Everyone,True,False,False,3,eniseistudio,Free
3,Medical Assistant,Education & Learning,4,18,5000,0,USD,"5,939",4,"Jun 24, 2017",2017-06-24,Everyone,True,False,False,7,eniseistudio,Free
4,Business Administration,Education & Learning,4,86,50000,0,USD,"5,837",4,"Jun 13, 2017",2017-10-06,Everyone,True,False,False,29,eniseistudio,Free

In [199]:
df['Content Rating'].value_counts()

Content Rating
Everyone           374924
Teen                40090
Mature 17+          13230
Everyone 10+        10333
Adults only 18+        29
Unrated                13
Name: count, dtype: int64

In [200]:
rating_groups = {
    'Everyone': ['Everyone', 'Everyone 10+'],

    'Teen': ['Teen'],

    'Mature': ['Mature 17+', 'Adults only 18+'],

    'Unrated': ['Unrated']
}

df['Content_Rating_Group'] = df['Content Rating']

for group, ratings in rating_groups.items():
    df.loc[
        df['Content Rating'].isin(ratings),
        'Content_Rating_Group'
    ] = group

In [201]:
df['Content Rating']=df['Content_Rating_Group']

In [202]:
df=df.drop(columns='Content_Rating_Group')

In [203]:
df.head()

,App Name,Category,Rating,Rating Count,Installs,Price,Currency,Size,Minimum Android,Released,Last update,Content Rating,Ad Supported,In app purchases,Editor Choice,Reviews,Developer,App Type
0,Logistics Management,Education & Learning,4,66,10000,0,USD,"5,939",4,"Jul 19, 2017",2017-07-19,Everyone,True,False,False,28,eniseistudio,Free
1,Estados Unidos Noticias,News & Magazines,4,8,1000,0,USD,"5,427",4,"May 5, 2017",2017-05-05,Everyone,True,False,False,3,eniseistudio,Free
2,Dental Assistant,Education & Learning,4,15,10000,0,USD,"5,837",4,"Jul 18, 2017",2017-07-18,Everyone,True,False,False,3,eniseistudio,Free
3,Medical Assistant,Education & Learning,4,18,5000,0,USD,"5,939",4,"Jun 24, 2017",2017-06-24,Everyone,True,False,False,7,eniseistudio,Free
4,Business Administration,Education & Learning,4,86,50000,0,USD,"5,837",4,"Jun 13, 2017",2017-10-06,Everyone,True,False,False,29,eniseistudio,Free

In [204]:
df.shape

(438619, 18)

In [205]:
df['Currency'].info()

<class 'pandas.core.series.Series'>
Index: 438619 entries, 0 to 450794
Series name: Currency
Non-Null Count   Dtype
--------------   -----
438619 non-null  object
dtypes: object(1)
memory usage: 6.7+ MB

In [206]:
# df.describe()

In [207]:
df['Last update'].isnull().sum()

np.int64(0)

In [208]:
df.head()

,App Name,Category,Rating,Rating Count,Installs,Price,Currency,Size,Minimum Android,Released,Last update,Content Rating,Ad Supported,In app purchases,Editor Choice,Reviews,Developer,App Type
0,Logistics Management,Education & Learning,4,66,10000,0,USD,"5,939",4,"Jul 19, 2017",2017-07-19,Everyone,True,False,False,28,eniseistudio,Free
1,Estados Unidos Noticias,News & Magazines,4,8,1000,0,USD,"5,427",4,"May 5, 2017",2017-05-05,Everyone,True,False,False,3,eniseistudio,Free
2,Dental Assistant,Education & Learning,4,15,10000,0,USD,"5,837",4,"Jul 18, 2017",2017-07-18,Everyone,True,False,False,3,eniseistudio,Free
3,Medical Assistant,Education & Learning,4,18,5000,0,USD,"5,939",4,"Jun 24, 2017",2017-06-24,Everyone,True,False,False,7,eniseistudio,Free
4,Business Administration,Education & Learning,4,86,50000,0,USD,"5,837",4,"Jun 13, 2017",2017-10-06,Everyone,True,False,False,29,eniseistudio,Free

In [209]:
df.describe()

,Rating,Rating Count,Installs,Price,Size,Minimum Android,Last update
count,"438,619","438,619","438,619","438,619","417,764","438,619",438619
mean,3,"14,354","870,552",0,"22,600",4,2020-01-07 09:33:24.266117376
min,0,3,0,0,5,1,2009-02-11 00:00:00
25%,0,43,500,0,"5,530",4,2019-06-25 00:00:00
50%,4,123,"5,000",0,"11,264",4,2020-07-31 00:00:00
75%,4,412,"50,000",0,"29,696",4,2021-03-09 00:00:00
max,5,"138,620,959","5,000,000,000",400,"1,572,864",8,2021-06-17 00:00:00
std,2,"574,927","33,295,857",4,"28,686",1,NaN

In [210]:
df_original = df.copy()

In [211]:
limit = df['Installs'].quantile(0.95)
outlier = df[df['Installs'] > limit]

In [212]:
(df['Installs'] > limit).sum()

np.int64(11871)

In [213]:
outlier[['App Name', 'Installs']].head(10)

                                              App Name  Installs
99   Coloring Games: Coloring Book, Painting, Glow ...  10000000
100        Baby Games - Piano, Baby Phone, First Words  10000000
101        Math Kids - Add, Subtract, Count, and Learn  10000000
102                       ABC Kids - Tracing & Phonics  10000000
103       Colors & Shapes - Kids Learn Color and Shape   5000000
104                      Magnifying Glass + Flashlight   5000000
105    Puzzle Kids - Animals Shapes and Jigsaw Puzzles  10000000
106                     Find The Differences - Spot it   5000000
141                    Learn to Read with Tommy Turtle   5000000
151                                  School of Dragons  10000000

In [214]:
outlier[['App Name', 'Installs', 'Rating', 'Rating Count']].head(20)

,App Name,Installs,Rating,Rating Count
99,"Coloring Games: Coloring Book, Painting, Glow ...",10000000,4,"29,898"
100,"Baby Games - Piano, Baby Phone, First Words",10000000,4,"13,842"
101,"Math Kids - Add, Subtract, Count, and Learn",10000000,4,"19,680"
102,ABC Kids - Tracing & Phonics,10000000,4,"62,518"
103,Colors & Shapes - Kids Learn Color and Shape,5000000,4,"8,573"
104,Magnifying Glass + Flashlight,5000000,5,"69,983"
105,Puzzle Kids - Animals Shapes and Jigsaw Puzzles,10000000,4,"14,797"
106,Find The Differences - Spot it,5000000,4,"31,627"
141,Learn to Read with Tommy Turtle,5000000,4,"21,762"
151,School of Dragons,10000000,4,"666,150"
154,Madagascar Surf n' Slides Free,5000000,4,"49,308"
157,Penguins: Dibble Dash,5000000,4,"34,949"
191,Flashlight ðŸ”¦ðŸŒŸðŸ’¡,10000000,4,"211,856"
193,123 Numbers - Count & Tracing,5000000,4,"9,009"
194,Multiplication Kids - Math Multiplication Tables,5000000,4,"3,916"
210,Zombie Ragdoll - Zombie Games,5000000,4,"72,179"
216,Finger Slayer,10000000,4,"73,544"
221,Bloody Monsters,5000000,4,"33,335"
239,"LinkedIn: Jobs, Business News & Social Networking",500000000,4,"2,047,007"
240,LinkedIn Learning: Online Courses to Learn Skills,5000000,5,"42,424"

In [215]:
print("Minimum installs in outliers:", outlier['Installs'].min())

Minimum installs in outliers: 5000000

In [216]:
print("Maximum installs in outliers:", outlier['Installs'].max())

Maximum installs in outliers: 5000000000

In [217]:
df.describe()

,Rating,Rating Count,Installs,Price,Size,Minimum Android,Last update
count,"438,619","438,619","438,619","438,619","417,764","438,619",438619
mean,3,"14,354","870,552",0,"22,600",4,2020-01-07 09:33:24.266117376
min,0,3,0,0,5,1,2009-02-11 00:00:00
25%,0,43,500,0,"5,530",4,2019-06-25 00:00:00
50%,4,123,"5,000",0,"11,264",4,2020-07-31 00:00:00
75%,4,412,"50,000",0,"29,696",4,2021-03-09 00:00:00
max,5,"138,620,959","5,000,000,000",400,"1,572,864",8,2021-06-17 00:00:00
std,2,"574,927","33,295,857",4,"28,686",1,NaN

In [218]:
# pontential outlier nikalne k liye

Q1 =  df['Installs'].quantile(0.25)
Q3 =  df['Installs'].quantile(0.75)

In [219]:
IQR = Q3 - Q1
print("IQR:",IQR)

IQR: 49500.0

In [220]:
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

In [221]:
outliers =df[ (df['Installs'] < lower_limit) | (df['Installs'] > upper_limit)]

In [222]:
outliers.head()

,App Name,Category,Rating,Rating Count,Installs,Price,Currency,Size,Minimum Android,Released,Last update,Content Rating,Ad Supported,In app purchases,Editor Choice,Reviews,Developer,App Type
10,Early Learning App - Kids Piano & Puzzles,Education & Learning,4,846,500000,0,USD,"27,648",4,"Aug 27, 2019",2020-06-04,Everyone,True,True,False,502,Early Learn,Free
11,Early Learning App For Kids,Education & Learning,4,"7,214",1000000,0,USD,"9,114",5,"Jun 15, 2019",2021-04-20,Everyone,True,False,False,"1,624",Early Learn,Free
38,Montessori Preschool,Education & Learning,4,"3,219",1000000,0,USD,"64,512",5,"Jul 3, 2017",2021-04-13,Everyone,Not Available,True,False,"1,936",EDOKI ACADEMY,Free
48,Kids Learning Box: Preschool,Education & Learning,4,"3,967",1000000,0,USD,"16,384",4,"Dec 31, 2016",2020-06-24,Everyone,True,True,False,"1,001",KidsAppBox,Free
49,First Words Baby Games: Toddler Learning Games,Education & Learning,4,968,500000,0,USD,"91,136",5,"May 8, 2018",2020-12-07,Everyone,True,True,False,274,KidsAppBox,Free

In [223]:
len(outliers)

49474

In [224]:
# pontential outlier all colmns
cols = ['Installs', 'Rating Count', 'Price', 'Size']

for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f'{col}: {len(outliers)} outliers')

Installs: 49474 outliers
Rating Count: 80636 outliers
Price: 27175 outliers
Size: 31147 outliers